# Generated by Django 5.1.4 on 2026-01-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_orderitem_product_price_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]